name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  branch:
    description: 'Current branch (typically, `github.ref`)'
    required: true
runs:
  using: 'node12'
  main: 'lib/main.js'
