name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm ci

      - run: npm run build

      - name: Prettier
        uses: harveyr/gh-action-prettier@releases/v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          patterns: src/**.ts

      - name: ESLint everything
        run: npx eslint src/**/**.ts __tests__/**/**.ts

      - run: npm test

      - run: npm run dist

      - uses: ./
        with:
          # TODO: make dashes vs. underscores consistent
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          dirs: dist
        if: contains(github.ref, 'refs/heads/versions/' )
