name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: npm ci

      - run: npm run build

      - name: Prettier
        uses: harveyr/gh-action-prettier@releases/v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          patterns: src/**.ts

      - name: ESLint
        uses: harveyr/gh-action-eslint@releases/v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          patterns: src/**.ts

      - run: npm test

      - run: |
          npm i @zeit/ncc
          ncc build lib/main.js -o dist

      - uses: ./
        with:
          # TODO: make dashes vs. underscores consistent
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          commit_dirs: dist
        if: contains(github.ref, 'refs/heads/versions/' )
